### ISSUE TITLE
Errors in the readme [joss.01693]

### ISSUE THREAD

**Issue by dawbarton** [LRydin/KramersMoyal#4]
I'm just going through your submission to JOSS and following through your readme I can't reproduce your results exactly.

1. The code errors since `kernel.epanechnikov` is an unknown name  (it should be `kernels.epanechnikov`).
2. The code errors saying that the first power should be zero. 

Fixing those two mistakes I then get the results that I plot using

```
plot(edges[0], kmc[1])  # the first coefficient
```

There is some distortion at the extremes (I presume to be expected due to low numbers of samples?) and it shows the linear trend demonstrated in the readme figures but the values are a factor of 1000 different.

A couple of minor points that don't affect the calculation but are more about style:
1. `y = np.zeros([time.size])` could simply be `y = np.zeros(time.size)`, and
2. `size=[time.size,1]` could simply be `size=time.size`.

**Comment by dawbarton** [comment]
Also, why is `bins` a numpy array rather than a simple integer? And the same for `powers` - is there a reason it is an array of arrays of integers rather than a simple array of integers?

**Comment by dawbarton** [comment]
Also, according to the JOSS checklist, you should state the dependencies of the package in your documentation (in this case, your readme since you have no separate documentation). I note that you mention it in the paper but it isn't immediately obvious and JOSS ask for it in the documentation rather than the paper.

In addition to the points already mentioned, I currently don't feel I can tick off

1. Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
     * There is no API documentation as far as I can see. I note there are docstrings but a bit more in the readme would be better. Also when the input is an array, a bit more information about what is expected would be helpful (for example, see my question about `powers` above).
2. Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
    * I didn't spot any of these.

**Comment by LRydin** [comment]
@dawbarton Sorry for the late reply. I am working with @fmeirinhos to try and reply to your comments.

We have not generated any documentation since I don't know how to do this at this stage. I was initially working on writing down the documentation inside the .py code, and then extended to a full documentation. As I am not an expert in this, it will certainly take a bit of time. 

Regarding the community guidelines, this clearly needs to be addressed. I will confer with @fmeirinhos on how to best set this up.

**Comment by fmeirinhos** [comment]
@dawbarton

Thank you for the revisions.

Here’s the changelog resulting from your remarks:

> The code errors since kernel.epanechnikov is an unknown name (it should be kernels.epanechnikov).

Corrected.


> The code errors saying that the first power should be zero.

The core algorithm needs the first power to be zero, but it now adds it automatically for internal use if the user hasn’t specified it.

> There is some distortion at the extremes (I presume to be expected due to low numbers of samples?) and it shows the linear trend demonstrated in the readme figures but the values are a factor of 1000 different.

This was a mismatch in the README, since the code wasn’t accounting for normalisation over the time steps; something that should be done for a correct physical interpretation, but not related with the algorithm. Corrected.

> A couple of minor points that don't affect the calculation but are more about style:
	• y = np.zeros([time.size]) could simply be y = np.zeros(time.size), and
	• size=[time.size,1] could simply be size=time.size.

Changed.


> Also, why is bins a numpy array rather than a simple integer? And the same for powers - is there a reason it is an array of arrays of integers rather than a simple array of integers?

Regarding bins, this is because the algorithm works for timeseries in n-dimensions, hence requiring an array of bins, each element specifying the binning in each dimension.
The same logic applies to powers. The user needs to specify the exponent in each direction. However, for the 1D case the user can also pass an array of powers, which then internally gets reshaped into a `(-1, 1)` form.

**Comment by kthyng** [comment]
It's helpful to reference the [paper review issue](https://github.com/openjournals/joss-reviews/issues/1693) from here too.

**Comment by kthyng** [comment]
@dawbarton Have your concerns here been addressed?

**Comment by dawbarton** [comment]
Yes, I'm happy.
